on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: GDG-Bhilai
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Welcome to the Org.'
          existingMemberMessage: 'You are already a member of our Organisation.'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
